services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:prd
    container_name: laravel-app-prd
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: "5432"
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: ${DB_PASSWORD}   # <- secret
      APP_KEY: ${APP_KEY}           # <- secret
      JWT_SECRET: ${JWT_SECRET}     # <- secret
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(function_exists(\"opcache_get_status\")?0:1);'"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - app_code:/var/www:rw
    networks:
      - backend

  web:
    image: nginx:alpine
    container_name: laravel-nginx-prd
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    expose:
      - "80"
    volumes:
      - app_code:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: laravel-postgres-prd
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: ${DB_PASSWORD}   # <- secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
  app_code:
